name: Deploy to Production

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4  # Adjust the Python version as needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          

    

      - name: Deploy to Production
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
    
          cp -r /path/to/your/static/files /var/www/html/


      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: project-artifacts
          path: |
            artifacts/  # Update this path to match the location of your artifacts
