name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4  # Adjust the Python version as needed

      - name: Install Dependencies
        run:  python -m pip install --upgrade pip  # Replace with your requirements file name

      - name: Build and Deploy
        run: |
          # Add commands to build and generate your static files
          # For example, if you're using a static site generator like Jekyll, Hugo, or Pelican, run the build command here.
          # Once your site is built, you can copy it to the deployment directory.

          # Copy the generated files to the public directory
          cp -r ./path/to/generated/files ./public

      - name: Deploy to GitHub Pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./public
          git commit -m "Deploy to GitHub Pages"
          git push origin main:gh-pages  # Push the changes to the gh-pages branch

